import time
from pathlib import Path

from loguru import logger as log
from PySide6.QtCore import QFile, QMarginsF
from PySide6.QtGui import QImage, QPageLayout, QPageSize, QPainter, QPdfWriter
from PySide6.QtPrintSupport import (
    QPrinter,
    QPrintPreviewDialog,
)
from PySide6.QtWidgets import QFileDialog

from src.Model.Data.const import ReclipMethod
from src.Model.Data.data import ReclipData, StyleData
from src.Model.Data.settings import (
    guiSettings,
    lineDetectorSettings,
    pathSettings,
    reclipSettings,
)
from src.Model.Data.type import FilePath, ImageArray, JsonPath
from src.Model.MainTask.Reclip import (
    ReclipThread,
    get_gap_line_index,
    style_restitched_clips,
)
from src.Model.utils import get_sysfonts, ndarray2qimage, read_image, read_images
from src.View import TabReclip_View
from src.ViewModel.binding.bind_data import bind_data


class TabReclip_VM(TabReclip_View):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.mainWindow = parent
        self.reclipThread: ReclipThread | None = None

        self.pathSettings = pathSettings
        self.reclipSettings = reclipSettings
        self.lineDetectorSettings = lineDetectorSettings
        self.styleData = StyleData()
        self.style_data_path: JsonPath | None = None

        bind_data(self.checkBox_live_preview, self.reclipSettings, "live_preview")
        bind_data(
            self.comboBox_clip_align, self.reclipSettings, "clip_align", use_index=True
        )
        bind_data(
            self.comboBox_reclip_method, self.reclipSettings, "method", use_index=True
        )
        bind_data(self.spinBox_clip_margin, self.reclipSettings, "clip_margin")
        bind_data(
            self.spinBox_each_line_bar_num, self.reclipSettings, "bar_num_each_line"
        )
        bind_data(
            self.spinBox_each_line_ength, self.reclipSettings, "bar_num_line_max_length"
        )
        bind_data(self.checkBox_clip_resize, self.reclipSettings, "clip_resize")
        bind_data(
            self.doubleSpinBox_resize_threshold,
            self.reclipSettings,
            "clip_resize_threshold",
        )

        bind_data(self.lineEdit_title, self.styleData, "title")
        bind_data(self.doubleSpinBox_margin_height, self.styleData, "margin_height")
        bind_data(self.doubleSpinBox_margin_width, self.styleData, "margin_width")
        bind_data(self.doubleSpinBox_margin_title, self.styleData, "margin_title")
        bind_data(self.checkBox_add_title, self.styleData, "add_title")
        bind_data(self.checkBox_add_page_num, self.styleData, "add_page_num")
        bind_data(self.comboBox_font_name, self.reclipSettings, "font_name")

        guiSettings.add_observer_handler(
            "imageViewer_show_tools", self.ImageViewer.toggle_tools
        )
        self.pathSettings.add_observer_handlers(
            ["main_out_dir", "score_title"], lambda v: self.handle_working_dir_changed()
        )
        self.reclipSettings.add_observer_handler(
            "method",
            lambda v: [
                self.spinBox_each_line_bar_num.setDisabled(
                    v == ReclipMethod.FILL_MAX_WIDTH
                ),
                self.spinBox_each_line_ength.setDisabled(
                    v == ReclipMethod.FIXED_BAR_NUM
                ),
            ],
        )

        self.pushButton_reclip.clicked.connect(self.start_reclip)
        self.pushButton_show_style.clicked.connect(self.show_style)
        self.pushButton_open_style.clicked.connect(self.handle_open_style)
        self.pushButton_save_style.clicked.connect(self.handle_save_style)
        self.pushButton_save_pdf.clicked.connect(self.save_pdf)
        self.pushButton_print_score.clicked.connect(self.printing_preview)

        self.copy_left: str = "This file was generated by Score-capture, a gpl licensed open source free sortware. Do Not sell or Pay for this!"

        self.sys_fonts = get_sysfonts()
        self.sys_font_names = list(self.sys_fonts.keys())
        self.check_font()
        self.update_font_name_combox()

    @property
    def font_path(self) -> FilePath:
        assert self.sys_fonts
        return self.sys_fonts[self.reclipSettings.font_name]

    def get_final_images(self) -> list[ImageArray] | None:
        working_dir = self.pathSettings.working_dir
        path = list(working_dir.glob(f"{working_dir.name}*[0-9]*"))
        if path == []:
            log.warning(
                self.tr("Image not found with wildcard: {}").format(
                    f"{working_dir.name}*[0-9]*"
                )
            )
            return None
        return read_images(path)

    def save_pdf(self) -> None:
        working_dir = self.pathSettings.working_dir
        if not (images := self.get_final_images()):
            return
        name = working_dir.name
        if self.styleData and self.styleData.add_title:
            name = self.styleData.title
        path = working_dir / name
        path, _ = QFileDialog.getSaveFileName(dir=path.as_posix(), filter=" (*.pdf)")
        if path == "":
            return
        qimages: list[QImage] = list(map(ndarray2qimage, images))

        pdf_file = QFile(path)
        pdf_file.open(QFile.OpenModeFlag.WriteOnly)
        pdf_writer = QPdfWriter(pdf_file)
        pdf_writer.setOutputIntent
        pdf_writer.setPageSize(QPageSize.PageSizeId.A4)
        pdf_writer.setPageMargins(QMarginsF(5, 5, 5, 5))
        pdf_writer.setPageOrientation(QPageLayout.Orientation.Portrait)  # vertical
        pdf_writer.setResolution(300)
        pdf_writer.setAuthor(self.copy_left)
        pdf_writer.setCreator("Score capture")
        ptr = QPainter(pdf_writer)
        for i, img in enumerate(qimages):
            pdf_writer.newPage() if i != 0 else None
            rect = ptr.viewport()
            img = img.scaledToWidth(rect.width())
            ptr.drawImage(0, 0, img)
        ptr.end()
        pdf_file.close()

    def printing_preview(self) -> None:
        if not self.get_final_images():
            return
        page_layout = QPageLayout()
        page_layout.setPageSize(QPageSize(QPageSize.PageSizeId.A4))  # A4 size
        page_layout.setOrientation(QPageLayout.Orientation.Portrait)  # Vertical
        page_layout.setMargins(QMarginsF(5, 5, 5, 5))  # margin
        preview = QPrintPreviewDialog(self)
        preview.printer().setPageLayout(page_layout)
        preview.paintRequested.connect(lambda: self.printing_score(preview.printer()))
        preview.exec()

    def printing_score(self, printer: QPrinter) -> None:
        working_dir = self.pathSettings.working_dir
        name = working_dir.name
        if (style_data := working_dir / "StyleData.json").exists():
            data = StyleData.load_from_file(style_data)
            name = data.title if data.add_title else name
        if not (images := self.get_final_images()):
            return
        qimages: list[QImage] = list(map(ndarray2qimage, images))

        printer.setResolution(300)
        printer.setCreator(self.copy_left)
        ptr = QPainter(printer)
        for i, img in enumerate(qimages):
            printer.newPage() if i != 0 else None
            rect = ptr.viewport()
            img = img.scaledToWidth(rect.width())
            ptr.drawImage(0, 0, img)
        ptr.end()

    def check_font(self) -> None:
        font_name = self.reclipSettings.font_name
        if font_name == "" or font_name not in self.sys_font_names:
            self.reclipSettings.font_name = self.sys_font_names[-1]

    def update_font_name_combox(self) -> None:
        self.comboBox_font_name.blockSignals(True)
        self.comboBox_font_name.clear()
        self.comboBox_font_name.addItems(self.sys_font_names)
        self.comboBox_font_name.setCurrentText(self.reclipSettings.font_name)
        self.comboBox_font_name.blockSignals(False)

    def flush_preview(self) -> None:
        working_dir = self.pathSettings.working_dir
        path = list(working_dir.glob(f"{working_dir.name}*[0-9]*"))
        if not path:
            log.info(
                self.tr("Image not found with wildcard: {}").format(
                    f"{working_dir.name}*[0-9]*"
                )
            )
            return
        self.ImageViewer.show_images(*path)

    def start_reclip(self) -> None:
        if self.reclipThread:
            log.warning(
                self.tr("Current reclip task is not finished. Please try again later.")
            )
            return
        if not self.pathSettings.working_dir.exists():
            log.warning(
                self.tr("Working dir does not exist: {}").format(
                    self.pathSettings.working_dir
                )
            )
            return

        self.reclipThread = ReclipThread(
            self.reclipSettings,
            self.lineDetectorSettings,
            self.pathSettings.working_dir,
            self.font_path,
            self.styleData,
        )
        self.reclipThread.finished.connect(self.flush_preview)
        self.reclipThread.destroyed.connect(lambda: setattr(self, "reclipThread", None))
        self.reclipThread.start()

    def show_style(self) -> None:
        working_dir = self.pathSettings.working_dir
        filename = working_dir.name + "-reclip" + reclipSettings.saving_format
        if not (working_dir / filename).exists():
            log.warning(
                self.tr("Recliped image not found: {}\nPlease do reclip first").format(
                    working_dir / filename
                )
            )
            return
        restitched_image = read_image(working_dir / filename)
        if not (working_dir / "ReclipData.json").exists():
            log.warning(
                self.tr("ReclipData not found: {}").format(
                    working_dir / "ReclipData.json"
                )
            )
            return
        reclip_data = ReclipData.load_from_file(working_dir / "ReclipData.json")

        style_restitched_clips(
            log,
            working_dir,
            self.reclipSettings,
            restitched_image,
            self.styleData,
            font_path=self.font_path,
            clip_height=reclip_data.clip_height
            if reclip_data.clip_height
            else get_gap_line_index(
                restitched_image,
                self.lineDetectorSettings,
                self.pathSettings.working_dir,
                log,
            ),
        )
        self.flush_preview()

    def load_style(self, path: JsonPath) -> None:
        if not path.exists():
            log.warning(self.tr("StyleData does not exist: {}").format(path))
            return
        self.style_data_path = path
        style = StyleData.load_from_file(path)
        for prop in StyleData.model_fields.keys():
            setattr(self.styleData, prop, getattr(style, prop))
        log.info(self.tr("StyleData Loaded: {}").format(path))

    def handle_working_dir_changed(self) -> None:
        working_dir = self.pathSettings.working_dir
        if self.style_data_path == (working_dir / "StyleData.json"):
            return
        if self.style_data_path and self.style_data_path.exists():
            self.styleData.save_to_file(self.style_data_path)
            self.style_data_path = None
        if (path := (working_dir / "StyleData.json")).exists():
            self.load_style(path)
        else:
            self.styleData.title = working_dir.name
            self.ImageViewer.clear()

    def handle_open_style(self) -> None:
        path, _ = QFileDialog.getOpenFileName(
            dir=self.pathSettings.working_dir.as_posix(),
            filter="StyleData (StyleData*.json)",
        )
        if path == "":
            return
        self.load_style(Path(path))
        self.show_style()

    def handle_save_style(self) -> None:
        name = f"StyleData_{time.strftime('%Y-%m-%d_%H-%M-%S')}.json"
        path, _ = QFileDialog.getSaveFileName(
            dir=(self.pathSettings.working_dir / name).as_posix(),
            filter="StyleData (*.json)",
        )
        if path == "":
            return
        self.styleData.save_to_file(Path(path))
        log.success(self.tr("StyleData saved as: {}").format(path))

    def closeEvent(self, event):
        if self.style_data_path:
            self.styleData.save_to_file(self.style_data_path)
        elif self.styleData != StyleData() and self.pathSettings.working_dir.exists():
            self.styleData.save_to_file(
                self.pathSettings.working_dir / "StyleData.json"
            )
        super().closeEvent(event)
