# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QStatusBar, QToolBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1300, 785)
        self.action_locate = QAction(MainWindow)
        self.action_locate.setObjectName(u"action_locate")
        self.action_locate.setMenuRole(QAction.MenuRole.NoRole)
        self.action_preview = QAction(MainWindow)
        self.action_preview.setObjectName(u"action_preview")
        self.action_preview.setMenuRole(QAction.MenuRole.NoRole)
        self.action_capture = QAction(MainWindow)
        self.action_capture.setObjectName(u"action_capture")
        self.action_capture.setCheckable(True)
        self.action_capture.setMenuRole(QAction.MenuRole.NoRole)
        self.action_stitch = QAction(MainWindow)
        self.action_stitch.setObjectName(u"action_stitch")
        self.action_stitch.setMenuRole(QAction.MenuRole.NoRole)
        self.action_reclip = QAction(MainWindow)
        self.action_reclip.setObjectName(u"action_reclip")
        self.action_reclip.setMenuRole(QAction.MenuRole.NoRole)
        self.action_select_folder = QAction(MainWindow)
        self.action_select_folder.setObjectName(u"action_select_folder")
        self.action_select_folder.setMenuRole(QAction.MenuRole.NoRole)
        self.action_open_folder = QAction(MainWindow)
        self.action_open_folder.setObjectName(u"action_open_folder")
        self.action_open_folder.setMenuRole(QAction.MenuRole.NoRole)
        self.action_rename_folder = QAction(MainWindow)
        self.action_rename_folder.setObjectName(u"action_rename_folder")
        self.action_rename_folder.setMenuRole(QAction.MenuRole.NoRole)
        self.action_output_pdf = QAction(MainWindow)
        self.action_output_pdf.setObjectName(u"action_output_pdf")
        self.action_print_score = QAction(MainWindow)
        self.action_print_score.setObjectName(u"action_print_score")
        self.action_about = QAction(MainWindow)
        self.action_about.setObjectName(u"action_about")
        self.actionMinimize = QAction(MainWindow)
        self.actionMinimize.setObjectName(u"actionMinimize")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1300, 33))
        self.menu_view = QMenu(self.menubar)
        self.menu_view.setObjectName(u"menu_view")
        self.menu_help = QMenu(self.menubar)
        self.menu_help.setObjectName(u"menu_help")
        self.menuLanguage = QMenu(self.menu_help)
        self.menuLanguage.setObjectName(u"menuLanguage")
        self.menu_file = QMenu(self.menubar)
        self.menu_file.setObjectName(u"menu_file")
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar_main = QToolBar(MainWindow)
        self.toolBar_main.setObjectName(u"toolBar_main")
        self.toolBar_main.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonIconOnly)
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar_main)
        self.toolBar_path = QToolBar(MainWindow)
        self.toolBar_path.setObjectName(u"toolBar_path")
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar_path)
        self.toolBar_view = QToolBar(MainWindow)
        self.toolBar_view.setObjectName(u"toolBar_view")
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar_view)

        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_view.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())
        self.menu_help.addAction(self.menuLanguage.menuAction())
        self.menu_help.addAction(self.action_about)
        self.menu_file.addAction(self.action_select_folder)
        self.menu_file.addAction(self.action_rename_folder)
        self.menu_file.addAction(self.action_open_folder)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_print_score)
        self.menu_file.addAction(self.action_output_pdf)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.actionMinimize)
        self.menu_file.addAction(self.actionExit)
        self.menu.addAction(self.action_locate)
        self.menu.addAction(self.action_preview)
        self.menu.addAction(self.action_capture)
        self.menu.addAction(self.action_stitch)
        self.menu.addAction(self.action_reclip)
        self.toolBar_main.addSeparator()
        self.toolBar_main.addAction(self.action_locate)
        self.toolBar_main.addAction(self.action_preview)
        self.toolBar_main.addAction(self.action_capture)
        self.toolBar_main.addAction(self.action_stitch)
        self.toolBar_main.addAction(self.action_reclip)
        self.toolBar_path.addAction(self.action_select_folder)
        self.toolBar_path.addAction(self.action_rename_folder)
        self.toolBar_path.addAction(self.action_open_folder)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Score Capture", None))
        self.action_locate.setText(QCoreApplication.translate("MainWindow", u"Locate", None))
#if QT_CONFIG(tooltip)
        self.action_locate.setToolTip(QCoreApplication.translate("MainWindow", u"Show locate window and update location.", None))
#endif // QT_CONFIG(tooltip)
        self.action_preview.setText(QCoreApplication.translate("MainWindow", u"Preview", None))
#if QT_CONFIG(tooltip)
        self.action_preview.setToolTip(QCoreApplication.translate("MainWindow", u"Preview the capture region.", None))
#endif // QT_CONFIG(tooltip)
        self.action_capture.setText(QCoreApplication.translate("MainWindow", u"Capture", None))
#if QT_CONFIG(tooltip)
        self.action_capture.setToolTip(QCoreApplication.translate("MainWindow", u"Start or stop capture.", None))
#endif // QT_CONFIG(tooltip)
        self.action_stitch.setText(QCoreApplication.translate("MainWindow", u"Stitch", None))
#if QT_CONFIG(tooltip)
        self.action_stitch.setToolTip(QCoreApplication.translate("MainWindow", u"Stitch images.", None))
#endif // QT_CONFIG(tooltip)
        self.action_reclip.setText(QCoreApplication.translate("MainWindow", u"Reclip", None))
#if QT_CONFIG(tooltip)
        self.action_reclip.setToolTip(QCoreApplication.translate("MainWindow", u"Reclip stitched image and generate final image.", None))
#endif // QT_CONFIG(tooltip)
        self.action_select_folder.setText(QCoreApplication.translate("MainWindow", u"Open", None))
#if QT_CONFIG(tooltip)
        self.action_select_folder.setToolTip(QCoreApplication.translate("MainWindow", u"Select a folder as working dir.", None))
#endif // QT_CONFIG(tooltip)
        self.action_open_folder.setText(QCoreApplication.translate("MainWindow", u"Reveal", None))
#if QT_CONFIG(tooltip)
        self.action_open_folder.setToolTip(QCoreApplication.translate("MainWindow", u"Reveal current working dir in explorer.", None))
#endif // QT_CONFIG(tooltip)
        self.action_rename_folder.setText(QCoreApplication.translate("MainWindow", u"Rename", None))
#if QT_CONFIG(tooltip)
        self.action_rename_folder.setToolTip(QCoreApplication.translate("MainWindow", u"Rename the folder and all image names including title.", None))
#endif // QT_CONFIG(tooltip)
        self.action_output_pdf.setText(QCoreApplication.translate("MainWindow", u"Save PDF", None))
#if QT_CONFIG(tooltip)
        self.action_output_pdf.setToolTip(QCoreApplication.translate("MainWindow", u"Save PDF", None))
#endif // QT_CONFIG(tooltip)
        self.action_print_score.setText(QCoreApplication.translate("MainWindow", u"Print", None))
        self.action_about.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionMinimize.setText(QCoreApplication.translate("MainWindow", u"Minimize", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.menu_view.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menu_help.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuLanguage.setTitle(QCoreApplication.translate("MainWindow", u"Language", None))
        self.menu_file.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"Action", None))
        self.toolBar_main.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar_main", None))
        self.toolBar_path.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
        self.toolBar_view.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

